
package pe.com.visanet.soap.ventas.generatesolicitude.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.12
 * 2018-11-05T10:05:43.694-05:00
 * Generated source version: 3.1.12
 */

@WebFault(name = "BaseFault", targetNamespace = "http://visanet.com.pe/soap/generic/visanetFault/ws/types")
public class BaseMessageFault extends Exception {
    
    private pe.com.visanet.soap.generic.visanetfault.ws.types.VisanetFaultType baseFault;

    public BaseMessageFault() {
        super();
    }
    
    public BaseMessageFault(String message) {
        super(message);
    }
    
    public BaseMessageFault(String message, Throwable cause) {
        super(message, cause);
    }

    public BaseMessageFault(String message, pe.com.visanet.soap.generic.visanetfault.ws.types.VisanetFaultType baseFault) {
        super(message);
        this.baseFault = baseFault;
    }

    public BaseMessageFault(String message, pe.com.visanet.soap.generic.visanetfault.ws.types.VisanetFaultType baseFault, Throwable cause) {
        super(message, cause);
        this.baseFault = baseFault;
    }

    public pe.com.visanet.soap.generic.visanetfault.ws.types.VisanetFaultType getFaultInfo() {
        return this.baseFault;
    }
}
