package pe.com.visanet.soap.ventas.generatesolicitude.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2018-11-05T10:05:43.718-05:00
 * Generated source version: 3.1.12
 * 
 */
@WebService(targetNamespace = "http://visanet.com.pe/soap/ventas/generatesolicitude/ws", name = "generatesolicitudePortTypeSOAP12")
@XmlSeeAlso({pe.com.visanet.soap.generic.visanetaudit.ws.types.ObjectFactory.class, pe.com.visanet.soap.ventas.generatesolicitude.ws.types.ObjectFactory.class, pe.com.visanet.soap.generic.visanetfault.ws.types.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface GeneratesolicitudePortTypeSOAP12 {

    @WebMethod(action = "http://visanet.com.pe/soap/ventas/generatesolicitude/ws/createSolicitude")
    public void createSolicitude(
        @WebParam(partName = "generatesolicitudeBaseHeaderRequest", name = "BaseHeaderRequest", targetNamespace = "http://visanet.com.pe/soap/ventas/generatesolicitude/ws/types", header = true)
        pe.com.visanet.soap.ventas.generatesolicitude.ws.types.BaseHeaderRequest generatesolicitudeBaseHeaderRequest,
        @WebParam(partName = "generatesolicitudeBaseBodyRequest", name = "BaseBodyRequest", targetNamespace = "http://visanet.com.pe/soap/ventas/generatesolicitude/ws/types")
        pe.com.visanet.soap.ventas.generatesolicitude.ws.types.BaseBodyRequest generatesolicitudeBaseBodyRequest,
        @WebParam(partName = "generatesolicitudeBaseHeaderResponse", mode = WebParam.Mode.OUT, name = "BaseHeaderResponse", targetNamespace = "http://visanet.com.pe/soap/ventas/generatesolicitude/ws/types", header = true)
        javax.xml.ws.Holder<pe.com.visanet.soap.ventas.generatesolicitude.ws.types.BaseHeaderResponse> generatesolicitudeBaseHeaderResponse,
        @WebParam(partName = "generatesolicitudeBaseBodyResponse", mode = WebParam.Mode.OUT, name = "BaseBodyResponse", targetNamespace = "http://visanet.com.pe/soap/ventas/generatesolicitude/ws/types")
        javax.xml.ws.Holder<pe.com.visanet.soap.ventas.generatesolicitude.ws.types.BaseBodyResponse> generatesolicitudeBaseBodyResponse
    ) throws BaseMessageFault;
}
