package pe.com.visanet.soap.ventas.generatesolicitude.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2018-11-05T10:05:43.742-05:00
 * Generated source version: 3.1.12
 * 
 */
@WebServiceClient(name = "generatesolicitudeService", 
                  wsdlLocation = "file:/C:/WORKSPACE_Eclipse/VISANET_PROPUESTA/Dummy_TEST_NEW/src/main/resources/wsdl/VISANETplantillaSOAP.wsdl",
                  targetNamespace = "http://visanet.com.pe/soap/ventas/generatesolicitude/ws") 
public class GeneratesolicitudeService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://visanet.com.pe/soap/ventas/generatesolicitude/ws", "generatesolicitudeService");
    public final static QName GeneratesolicitudePortSOAP12 = new QName("http://visanet.com.pe/soap/ventas/generatesolicitude/ws", "generatesolicitudePortSOAP12");
    public final static QName GeneratesolicitudePortSOAP11 = new QName("http://visanet.com.pe/soap/ventas/generatesolicitude/ws", "generatesolicitudePortSOAP11");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/WORKSPACE_Eclipse/VISANET_PROPUESTA/Dummy_TEST_NEW/src/main/resources/wsdl/VISANETplantillaSOAP.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GeneratesolicitudeService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/WORKSPACE_Eclipse/VISANET_PROPUESTA/Dummy_TEST_NEW/src/main/resources/wsdl/VISANETplantillaSOAP.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public GeneratesolicitudeService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GeneratesolicitudeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GeneratesolicitudeService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public GeneratesolicitudeService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public GeneratesolicitudeService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public GeneratesolicitudeService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns GeneratesolicitudePortTypeSOAP12
     */
    @WebEndpoint(name = "generatesolicitudePortSOAP12")
    public GeneratesolicitudePortTypeSOAP12 getGeneratesolicitudePortSOAP12() {
        return super.getPort(GeneratesolicitudePortSOAP12, GeneratesolicitudePortTypeSOAP12.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GeneratesolicitudePortTypeSOAP12
     */
    @WebEndpoint(name = "generatesolicitudePortSOAP12")
    public GeneratesolicitudePortTypeSOAP12 getGeneratesolicitudePortSOAP12(WebServiceFeature... features) {
        return super.getPort(GeneratesolicitudePortSOAP12, GeneratesolicitudePortTypeSOAP12.class, features);
    }


    /**
     *
     * @return
     *     returns GeneratesolicitudePortTypeSOAP11
     */
    @WebEndpoint(name = "generatesolicitudePortSOAP11")
    public GeneratesolicitudePortTypeSOAP11 getGeneratesolicitudePortSOAP11() {
        return super.getPort(GeneratesolicitudePortSOAP11, GeneratesolicitudePortTypeSOAP11.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GeneratesolicitudePortTypeSOAP11
     */
    @WebEndpoint(name = "generatesolicitudePortSOAP11")
    public GeneratesolicitudePortTypeSOAP11 getGeneratesolicitudePortSOAP11(WebServiceFeature... features) {
        return super.getPort(GeneratesolicitudePortSOAP11, GeneratesolicitudePortTypeSOAP11.class, features);
    }

}
